"""empty message

Revision ID: 880d2ecbf315
Revises: 
Create Date: 2019-09-30 17:16:44.337961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '880d2ecbf315'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=64), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_filename'), 'video', ['filename'], unique=True)
    op.create_index(op.f('ix_video_likes'), 'video', ['likes'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_likes'), table_name='video')
    op.drop_index(op.f('ix_video_filename'), table_name='video')
    op.drop_table('video')
    # ### end Alembic commands ###
